name: PR Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Gradle Build Action
      uses: gradle/gradle-build-action@v2
    - name: Build with PTS (relevant tests)
      run: ./gradlew build -Dpts.enabled=true
